### ISSUE TITLE
flags not taken into account in the disasm

### ISSUE THREAD

**Issue by radare** [rizinorg/rz-ghidra#16] opened 2019-08-21 09:20 UTC
![IMAGE 2019-08-21 11:20:14](https://user-images.githubusercontent.com/917142/63419761-a5f9c180-c405-11e9-9191-e27683a466f8.jpg)

**Comment by thestr4ng3r** [comment] 2019-11-28 09:42
ping

**Comment by XVilka** [comment] 2021-03-12 09:08
Closing since there is no way to reproduce and it's unclear what is the reason of the problem.

**Closed by XVilka** 2021-03-12 09:08 UTC
