### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jacobrosenthal** [rizinorg/rz-ghidra#46] opened 2019-09-30 22:18 UTC
sys/user.sh
r2pm init
r2pm update
brew install pkg-config cmake
r2pm -i r2ghidra-dec

pdg

radare2/env.sh: line 65: 61486 Segmentation fault: 11  R2_ENV_IS_SET=1 R2_LIBR_PLUGINS=${pfx}/lib/radare2 PATH=$pfx/bin:${PATH} LD_LIBRARY_PATH=$pfx/lib:$LD_LIBRARY_PATH DYLD_LIBRARY_PATH=$pfx/lib:$DYLD_LIBRARY_PATH PKG_CONFIG_PATH=$pfx/lib/pkgconfig:$PKG_CONFIG_PATH "${1}" "${2}" "${3}" "${4}"
$ 

Module version mismatch /Users/jacobrosenthal/.local/share/radare2/plugins/core_pdd.dylib (3.0.0-git) vs (4.0.0-git)

r2pm -i `r2pm -l`

Module version mismatch /Users/jacobrosenthal/.local/share/radare2/plugins/core_pdd.dylib (3.0.0-git) vs (4.0.0-git)

$ r2 -V
3.9.0-73-g5193b7284  r2
3.9.0-73-g5193b7284  r_anal
3.9.0-73-g5193b7284  r_lib
3.9.0-73-g5193b7284  r_egg
3.9.0-73-g5193b7284  r_asm
3.9.0-73-g5193b7284  r_bin
3.9.0-73-g5193b7284  r_cons
3.9.0-73-g5193b7284  r_flag
3.9.0-73-g5193b7284  r_core
3.9.0-73-g5193b7284  r_crypto
3.9.0-73-g5193b7284  r_bp
3.9.0-73-g5193b7284  r_debug
3.9.0-73-g5193b7284  r_main
3.9.0-73-g5193b7284  r_hash
3.9.0-73-g5193b7284  r_fs
3.9.0-73-g5193b7284  r_io
3.9.0-73-g5193b7284  r_magic
3.9.0-73-g5193b7284  r_parse
3.9.0-73-g5193b7284  r_reg
3.9.0-73-g5193b7284  r_sign
3.9.0-73-g5193b7284  r_search
3.9.0-73-g5193b7284  r_syscall
3.9.0-73-g5193b7284  r_util

make uninstall
make purge
make system-purge

sys/user.sh
r2pm init
r2pm update
r2pm -i r2ghidra-dec

$ r2 -vv
radare2 4.0.0-git 23068 @ darwin-x86-64 git.3.9.0-81-g2bd96a56d
commit: 2bd96a56d14c3fa7d8e24123c8f95aa5d35da9be build: 2019-09-30__09:34:48
$ r2 -V
3.9.0-81-g2bd96a56d  r2
3.9.0-81-g2bd96a56d  r_anal
3.9.0-81-g2bd96a56d  r_lib
3.9.0-81-g2bd96a56d  r_egg
3.9.0-81-g2bd96a56d  r_asm
3.9.0-81-g2bd96a56d  r_bin
3.9.0-81-g2bd96a56d  r_cons
3.9.0-81-g2bd96a56d  r_flag
3.9.0-81-g2bd96a56d  r_core
3.9.0-81-g2bd96a56d  r_crypto
3.9.0-81-g2bd96a56d  r_bp
3.9.0-81-g2bd96a56d  r_debug
3.9.0-81-g2bd96a56d  r_main
3.9.0-81-g2bd96a56d  r_hash
3.9.0-81-g2bd96a56d  r_fs
3.9.0-81-g2bd96a56d  r_io
3.9.0-81-g2bd96a56d  r_magic
3.9.0-81-g2bd96a56d  r_parse
3.9.0-81-g2bd96a56d  r_reg
3.9.0-81-g2bd96a56d  r_sign
3.9.0-81-g2bd96a56d  r_search
3.9.0-81-g2bd96a56d  r_syscall
3.9.0-81-g2bd96a56d  r_util

pdg

radare2/env.sh: line 65: 61486 Segmentation fault: 11  R2_ENV_IS_SET=1 R2_LIBR_PLUGINS=${pfx}/lib/radare2 PATH=$pfx/bin:${PATH} LD_LIBRARY_PATH=$pfx/lib:$LD_LIBRARY_PATH DYLD_LIBRARY_PATH=$pfx/lib:$DYLD_LIBRARY_PATH PKG_CONFIG_PATH=$pfx/lib/pkgconfig:$PKG_CONFIG_PATH "${1}" "${2}" "${3}" "${4}"
$

**Comment by thestr4ng3r** [comment] 2019-11-28 09:44
Is this still relevant? Please update everything to the latest masters and share the binary + function offset if you still can reproduce.

**Comment by XVilka** [comment] 2021-03-11 09:42
I am closing this since no answer for more than a year. If it's still happening, please open a new issue.

**Closed by XVilka** 2021-03-11 09:42 UTC
