### ISSUE TITLE
Pointer to strings not resolved

### ISSUE THREAD

**Issue by radare** [rizinorg/rz-ghidra#93] opened 2020-03-23 15:35 UTC
**Describe the issue**

Decompiling objc code results in useless code because the strings are not resolved, ths screenshot shows it all

**How to reproduce?**

Get any objc binary from iOS

**Expected behavior**

**Possible fix**

honor afs function signature and resolve the pointer to string pointers

**Screenshots**

![IMAGE 2020-03-23 16:34:20](https://user-images.githubusercontent.com/917142/77333739-28dc5500-6d24-11ea-8365-23e166f8de1d.jpg)

**Additional context**

**Comment by ITAYC0HEN** [comment] 2020-03-23 15:44
Thank you for reporting an issue to r2ghidra-dec :)
As it seems, you did not provide a binary with your submission and instructions to reproduce the erroneous behavior. Please attach the binary to the issue as well as steps to reproduce, for example - a specific function or address that demonstrates the issue. This will help the dev team of r2ghidra-dec to solve the issue.

**Comment by radare** [comment] 2020-03-23 16:34
I did. In private because its not a shareable sample. Enotime to cook a hello world or fins another sample but should be reproducible easily

**Comment by XVilka** [comment] 2023-01-23 04:23
Closing since there there is no way to reproduce.

**Closed by XVilka** 2023-01-23 04:23 UTC
Labels: test-required
